### ISSUE TITLE
App crashes on launch.

### ISSUE THREAD

**Issue by naleach** [AgoraIO/Basic-Audio-Broadcasting#5]
I am able to get the project compiling but it crashes as soon as it launches. I've tested this on a physical Samsung Galaxy S8 and an emulated Pixel 3. Both produce the same results.

It seems to be crashing on line 15 in AGApplication.java.

```
mWorkerThread.start();
```
It produces the error:

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: io.agora.openlive.voice.only, PID: 13997
    java.lang.RuntimeException: NEED TO check rtc sdk init fatal error
    java.lang.IllegalArgumentException: cannot initialize Agora Rtc Engine, error=101
        at io.agora.rtc.internal.RtcEngineImpl.nativeObjectInit(Native Method)
        at io.agora.rtc.internal.RtcEngineImpl.<init>(RtcEngineImpl.java:185)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:65)
        at io.agora.openlive.voice.only.model.WorkerThread.ensureRtcEngineReadyLock(WorkerThread.java:183)
        at io.agora.openlive.voice.only.model.WorkerThread.run(WorkerThread.java:97)
    
        at io.agora.openlive.voice.only.model.WorkerThread.ensureRtcEngineReadyLock(WorkerThread.java:186)
        at io.agora.openlive.voice.only.model.WorkerThread.run(WorkerThread.java:97)
```

I have tried integrating the SDK through JCenter using the provided Gradel configuration as well as manually integrating the SDK that I downloaded from Agora.

**Comment by naleach** [comment]
My key was incorrect.
